import numpy as np
import pandas as pd
#to measure similarity between target and data points use eucliedian 
def eucl(x1, x2):  
    # ---- Code generated by Claude ----
    diff = x1 - x2
    squared = diff ** 2
    total = squared.sum()
    return total ** 0.5
    # ---- End Claude code ----
# Indentifying neighbors
def knn(data,pt,k):
    # ---- Code generated by Claude ----
    n = data.shape[0]
    distances = np.empty(n)
    for i in range(n):
        distances[i] = eucl(data[i], pt)
    nearest_indices = np.argsort(distances)[:k]
    neighbour = nearest_indices.tolist()
    # ---- End Claude code ----
    return neighbour
# prediction
data=pd.read_csv("simulation_500.csv")
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values
pt = X[0]
k = 3
neighbour = knn(X, pt, k)
labels = [y[i] for i in neighbour]
prediction = max(set(labels), key=labels.count)
print("Neighbors:", neighbour)
print("Prediction:", prediction)