import numpy as np
import pandas as pd
# similarity between two points we use euclidean distance
def eucl(x1, x2):
    # ---- Code generated by Claude ----
    diff = x1 - x2
    squared = diff ** 2
    total = squared.sum()
    return total ** 0.5
    # ---- End Claude code ----
# find the k closest rows to our point
def knn(data, pt, k):
    # ---- Code generated by Claude ----
    n = data.shape[0]
    distances = np.empty(n)
    for i in range(n):
        distances[i] = eucl(pt, data[i])
    nearest_indices = np.argsort(distances)[:k]
    neighbour = nearest_indices.tolist()
    # ---- End Claude code ----
    return neighbour
# weight by distance
def weighted(data, y, pt, k):
    # ---- Code generated by Claude ----
    neighbour = knn(data, pt, k)
    votes = {}
    for i in neighbour:
        d = eucl(pt, data[i])
        w = 1 / (d + 0.000000001)
        label = y[i]
        votes[label] = votes.get(label, 0) + w
    prediction = max(votes, key=votes.get)
    # ---- End Claude code ----
    return prediction, neighbour, votes
data = pd.read_csv("simulation_500.csv")
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values
pt = X[0]
k = 3
pred, nb, votes = weighted(X, y, pt, k)
print("Neighbors:", nb)
print("Distances:", [float(round(eucl(pt, X[i]), 4)) for i in nb])
print("Weighted votes:",{int(c): float(round(w, 4))for c, w in votes.items()})
print("Prediction:", pred)
print("True label:", y[0])