import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

def fit(X_train,y_train):
    # ---- Code generated by Claude ----
    return X_train, y_train
    # ---- End Claude code ----

def predict(X_train,y_train,X_test):
    # ---- Code generated by Claude ----
    y_pred = []
    for pt in X_test:
        distances = np.sqrt(np.sum((X_train - pt) ** 2, axis=1))
        nearest_indices = np.argsort(distances)[:3]
        labels = [y_train[i] for i in nearest_indices]
        counts = {}
        for label in labels:
            counts[label] = counts.get(label, 0) + 1
        prediction = max(counts, key=counts.get)
        y_pred.append(prediction)
    return y_pred
    # ---- End Claude code ----

def score(y_test,y_pred):
    # ---- Code generated by Claude ----
    y_test_arr = np.array(y_test)
    y_pred_arr = np.array(y_pred)
    correct = np.sum(y_test_arr == y_pred_arr)
    return correct / len(y_test)
    # ---- End Claude code ----

data=pd.read_csv("simulation_500.csv")
X=data.iloc[:,:-1].values
y=data.iloc[:,-1].values
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)
X_train,y_train=fit(X_train,y_train)
y_pred=predict(X_train,y_train,X_test)
print("Predictions:",y_pred)
print("Score:",score(y_test,y_pred))