import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

data=pd.read_csv("simulation_500.csv")
X=data.iloc[:,:-1].values
y=data.iloc[:,-1].values
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

# to measure similarity between target and data points use eucliedian
def eucl(x1,x2):
    # ---- Code generated by Claude ----
    diff = x1 - x2
    squared = diff ** 2
    total = squared.sum()
    return total ** 0.5
    # ---- End Claude code ----
# Identifying neighbors
def knn(data,pt,k):
    # ---- Code generated by Claude ----
    distances = np.sqrt(np.sum((data - pt) ** 2, axis=1))
    nearest_indices = np.argsort(distances)[:k]
    neighbour = nearest_indices.tolist()
    # ---- End Claude code ----
    return neighbour

# prediction
def predict(X_train,y_train,X_test,k):
    # ---- Code generated by Claude ----
    y_pred = []
    for pt in X_test:
        neighbour = knn(X_train, pt, k)
        labels = [y_train[i] for i in neighbour]
        counts = {}
        for label in labels:
            counts[label] = counts.get(label, 0) + 1
        prediction = max(counts, key=counts.get)
        y_pred.append(prediction)
    # ---- End Claude code ----
    return y_pred

def score(y_test,y_pred):
    # ---- Code generated by Claude ----
    y_test_arr = np.array(y_test)
    y_pred_arr = np.array(y_pred)
    correct = np.sum(y_test_arr == y_pred_arr)
    return correct / len(y_test)
    # ---- End Claude code ----

k_values=[1,3,5,7,9]
own=[]
sk=[]
for k in k_values:
    y_pred=predict(X_train,y_train,X_test,k)
    own.append(score(y_test,y_pred))
    neigh=KNeighborsClassifier(n_neighbors=k)
    neigh.fit(X_train,y_train)
    sk.append(neigh.score(X_test,y_test))
print("Own:",own)
print("Sk:",sk)

plt.plot(k_values,own,marker='o',label='Own')
plt.plot(k_values,sk,marker='s',label='Sk')
plt.xlabel("k")
plt.ylabel("Acc")
plt.title("Acc vs k")
plt.legend()
plt.show()