import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

data=pd.read_csv("simulation_500.csv")
X=data.iloc[:,:-1].values
y=data.iloc[:,-1].values
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

def predict(X_train,y_train,X_test,k):
    # ---- Code generated by Claude ----
    y_pred = []
    for pt in X_test:
        distances = np.sqrt(np.sum((X_train - pt) ** 2, axis=1))
        nearest_indices = np.argsort(distances)[:k]
        votes = {}
        for i in nearest_indices:
            dist = distances[i]
            # small distance gives big weight and division by 0 shouldnt be possible so we add 0.000000001
            weight = 1 / (dist + 0.000000001)
            label = y_train[i]
            votes[label] = votes.get(label, 0) + weight
        prediction = max(votes, key=votes.get)
        y_pred.append(prediction)
    # ---- End Claude code ----
    return y_pred

def score(y_test,y_pred):
    # ---- Code generated by Claude ----
    y_test_arr = np.array(y_test)
    y_pred_arr = np.array(y_pred)
    correct = np.sum(y_test_arr == y_pred_arr)
    return correct / len(y_test)
    # ---- End Claude code ----

k_values=[1,3,5,7,9]
weighted=[]
sk=[]
for k in k_values:
    y_pred=predict(X_train,y_train,X_test,k)
    weighted.append(score(y_test,y_pred))
    neigh=KNeighborsClassifier(n_neighbors=k,weights='distance')
    neigh.fit(X_train,y_train)
    sk.append(neigh.score(X_test,y_test))

print("Weighted KNN:",weighted)
print("Sklearn Weighted KNN:",sk)
plt.plot(k_values,weighted,marker='o',label='Own Weighted KNN')
plt.plot(k_values,sk,marker='s',label='Sklearn Weighted KNN')
plt.xlabel("k")
plt.ylabel("Accuracy")
plt.title("Weighted KNN Comparison")
plt.legend()
plt.show()